### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by willnationsdev** [thoth-org/Thoth.Elmish.FormBuilder#17]
I have not seen any specifics as to which licensed has been assigned to this repository. Presumably, it is an open-source library(?), but I cannot find the details. I'm hoping that I will have the ability to port some of this code to a Bolero.FormBuilder library.

**Comment by MangelMaxime** [comment]
Hello @willnationsdev 

I kind of miss porting the license file when moving the repository.

It is licensed under MIT: https://github.com/thoth-org/Thoth.Elmish.FormBuilder/blob/master/LICENSE.md

So in theory from what I understand of the license, you can do anything as long as you mention the license.
